// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package database

import (
	"time"
)

type Comment struct {
	ID              int64
	CreatedAt       time.Time
	UpdatedAt       time.Time
	Content         string
	PostID          int64
	UserID          int64
	ParentCommentID *int64
}

type CommentVote struct {
	CommentID int64
	UserID    int64
	Liked     bool
}

type Post struct {
	ID          int64
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Title       string
	Description *string
	UserID      int64
}

type PostResource struct {
	PostID     int64
	ResourceID int64
}

type PostVote struct {
	PostID int64
	UserID int64
	Liked  bool
}

type Resource struct {
	ID        int64
	CreatedAt time.Time
	UpdatedAt time.Time
	Kind      string
	FilePath  string
	MimeType  string
	UserID    int64
}

type User struct {
	ID            int64
	CreatedAt     time.Time
	UpdatedAt     time.Time
	FirstName     string
	LastName      string
	EmailAddress  string
	EmailVerified bool
	PasswordHash  string
}
