// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package database

import (
	"context"
)

type Querier interface {
	CommentByID(ctx context.Context, arg CommentByIDParams) (*Comment, error)
	DeleteComment(ctx context.Context, arg DeleteCommentParams) error
	DeletePost(ctx context.Context, arg DeletePostParams) error
	DeleteUser(ctx context.Context, arg DeleteUserParams) error
	InsertComment(ctx context.Context, arg InsertCommentParams) error
	InsertPost(ctx context.Context, arg InsertPostParams) error
	InsertUser(ctx context.Context, arg InsertUserParams) error
	PostByID(ctx context.Context, arg PostByIDParams) (*Post, error)
	PostsByRating(ctx context.Context) ([]*Post, error)
	UpdateComment(ctx context.Context, arg UpdateCommentParams) error
	UpdatePost(ctx context.Context, arg UpdatePostParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
	UpsertCommentVote(ctx context.Context, arg UpsertCommentVoteParams) error
	UpsertPostVote(ctx context.Context, arg UpsertPostVoteParams) error
	UserByEmail(ctx context.Context, arg UserByEmailParams) (*User, error)
	UserByID(ctx context.Context, arg UserByIDParams) (*User, error)
}

var _ Querier = (*Queries)(nil)
