root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  args_bin = ["-c", "configs/config.development.yml"]
  bin = "./bin/andy"
  cmd = "make"
  delay = 1000
  exclude_dir = ["node_modules", "tmp", "bin", "web/app/dist", "web/app/node_modules"]
  exclude_file = []
  exclude_regex = ["_test.go", ".sql.go"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = ["go", "gotmpl", "ts", "css"]
  include_file = []
  kill_delay = "250ms"
  log = "build-errors.log"
  poll = false
  poll_interval = 0
  post_cmd = []
  pre_cmd = []
  rerun = false
  rerun_delay = 500
  send_interrupt = true
  stop_on_error = true

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  time = false

[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = true
  keep_scroll = true
